package com.ms.template.model.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "user")
public class DynamoUserDao {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String userId;
    @DynamoDBAttribute
    String userName;
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    LocalDateTime createdDate;
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    LocalDateTime modifiedDate;

    public DynamoUserDao(String userName) {
        this.userName = userName;
    }
}
